Bugs my teammate found and their fixes (Also includes other bugs I found in the same function)
----------------------------------------------------------------------------------------------
unittest 1: playcard
Error: all of the tests failed due to a bad exit status from the play card function.

I used my partner's test and the playdom.c file to debug the function. The error is in this line 
if ( state->numActions < 1 )
For my partner's test, the numActions for the gamestate passed to the function is 0. This is where the error is. 
To locate the origin, i used playdom.c to see that playCard doesn't seem to have a bug. Depending on how the function is called,
numActions for the function needs to be correctly incremented in the previous function. The function
correctly executes for playdom when the turn is initialized for each player. Another way to fix this
is to find where playCard is being called. Before the function is called for the current player, the numActions
are first checked to see if the current player is able to play a card.
if (state->numActions<1)
{
	endturn(state);
}
else{
	playcard(state);
}


unitTest 2: game is over
Error: 991 of 2000 tests had a negative supply count indicating either a bad game state/intialization
Similar to the first test case, I used my partner's code to further investigate the bugs found.
The errors are being generated by this code of the test.
    for (i = 0; i < sizeof(struct gameState); i++) {
      //fill gamestate with random bits between 0-256 using ofset
      ((char*)&G)[i] = floor(Random() * 256);
    }
This indicates a bad game state initialization. To fix this, I added a check for a negative supply count.
 j = 0;
  for (i = 0; i < 27; i++)
    {
      if (state->supplyCount[i] <= 0)
	{
	  j++;
	}
    }
  if ( j >= 3)
    {
      return 1;
    }
to test for negative supplyCount numbers. 

A bug I found when testing this function with my tests is that not all piles are being tested. The
error is in the following code:
//if three supply pile are at 0, the game ends
  j = 0;
  for (i = 0; i < 25; i++)
	  
I changed the above to
  //if three supply pile are at 0, the game ends
  j = 0;
  for (i = 0; i < 27; i++)
to account for the last 2 cards, treasure_map and sea_hag.	  


unitTest 4: endturn
Error: I had to alter my unit test4 so that the assert on memcopy size mismatch threw an error instead 
of exitted using assert. Once the assert was removed a segfault occured.
Again, the error is in the gamestate initialization.
    for (i = 0; i < sizeof(struct gameState); i++) {
      //fill gamestate with random bits between 0-256 using ofset
      ((char*)&G)[i] = floor(Random() * 256);
    }
The errors that are being thrown is that current player's turn has not changed and the handcount
did not increase.
Added
state->handCount[state->whoseTurn]+5;
to ensure that the handCount of current player increases since you start off with 5 cards in your hand in
the beginning of each of your turn. 
if (currentPlayer < (state->numPlayers - 1)){ 
    state->whoseTurn = currentPlayer + 1;//Still safe to increment
  }
  else{
    state->whoseTurn = 0;//Max player has been reached, loop back around to player 1
  }
This is included to ensure that the turn changes and the next player is set.  


cardtest1: adventurerCard
had to alter name of the function and accept the returned int
new code
    int success
    success=playAdventurer(struct gameState *state);
    if(success!=0){
        #if (NOISY_TEST == 1)
        printf("error inside play test adventurer");
        #endif
        return 1;
    }
error:segfault
Bug found when testing player who plays the adventurer card. deckCount is incremented when
it should remain unchanged. 
Another bug found when testing handCount. handCount of the player that played adventurer
card decreased instead of increased.
Code changed for drawntreasure count (the bug I introduced)
	while(drawntreasure<2){
	if (state->deckCount[currentPlayer] <1){//if the deck is empty we need to shuffle discard and add to deck
	  shuffle(currentPlayer, state);
	}
The bugs seem to be in drawCard, as the count is fine before drawCard is called within the playAdventurer function.
	
Card Test3: Smithy
error: segfault
Bug found when checking handCount
Code added and changed
Moved this out of if statement.
    state->handCount[player]++;//Increment hand count
Tests pass. The above code is found in the drawCard function.  


Card Test 4:village
error: segfault
Code changed
discardCard(handPos, currentPlayer, state, 0);
This was a bug that I introduced.
Again, drawCard was throwing the errors and this was already fixed for a previous bug.

Since all of these bugs were segfaults, I used the debugger and my own tests to find the bugs in my programs



